; FutureGrid Portal drush make file
; futuregrid.make
; author:	Matthew R Hanlon
; date:		2012-03-02

; Drupal core version
core = 6.x

api = 2

; Modules
projects[] = drupal
projects[account_reminder][version] = "1.2"
projects[acl][version] = "1.4"
projects[action_email_role][version] = "1.11"
projects[admin_menu][version] = "1.8"
projects[advanced_help][version] = "1.2"
projects[autoload][version] = "2.1"
projects[backup_migrate][version] = "2.4"
projects[better_formats][version] = "1.2"
projects[biblio][version] = "1.17"
projects[blocktheme][version] = "1.2"
projects[ctools][version] = "1.8"
projects[captcha][version] = "2.4"
projects[graphviz_filter][version] = "1.6"
projects[charts][version] = "1.0"
projects[charts_graphs][version] = "2.7"
projects[computed_field][version] = "1.0-beta5"
projects[conditional_fields][version] = "2.0"
projects[contemplate][version] = "1.2"
projects[cck][version] = "2.9"
projects[dashboard][version] = "2.1"
projects[data][version] = "1.0"
projects[date][version] = "2.8"
projects[drupal_tweaks][version] = "1.x-dev"
projects[diff][version] = "2.3"
projects[wysiwyg_imageupload][version] = "2.9"
projects[embed_gmap][version] = "1.2"
projects[emptyparagraphkiller][version] = "1.0-beta1"
projects[fancybox][version] = "1.x-dev"
projects[faq][version] = "1.12"
projects[faq_ask][version] = "2.1"
projects[field_permissions][version] = "1.0"
projects[filefield][version] = "3.10"
projects[filefield_paths][version] = "1.4"
projects[fivestar][version] = "1.19"
projects[flag][version] = "1.3"
projects[flexifilter][version] = "1.2"
projects[forum_access][version] = "1.7"
projects[fpa][version] = "2.3"
projects[front][version] = "1.3"
projects[globalredirect][version] = "1.x-dev"
projects[gmap][version] = "1.1"
projects[google_analytics][version] = "3.3"
projects[homebox][version] = "3.0-beta5"
projects[image][version] = "1.1"
projects[image_resize_filter][version] = "1.13"
projects[imageapi][version] = "1.10"
projects[imagecache][version] = "2.0-beta12"
projects[imagecache_actions][version] = "1.8"
projects[imagecache_profiles][version] = "1.3"
projects[imce][version] = "2.3"
projects[img_assist][version] = "2.0-alpha4"
projects[inputstream][version] = "1.0"
projects[jquery_ui][version] = "1.5"
projects[jquery_ui_dialog][version] = "1.10"
projects[jquery_update][version] = "2.0-alpha1"
projects[libraries][version] = "1.0"
projects[linkchecker][version] = "2.5"
projects[location][version] = "3.1"
projects[logintoboggan][version] = "1.10"
projects[markdown][version] = "1.2"
projects[masquerade][version] = "1.7"
projects[messaging][version] = "2.4"
projects[mimemail][version] = "1.0"
projects[modalframe][version] = "1.7"
projects[nodeaccess][version] = "1.3"
projects[nodequeue][version] = "2.11"
projects[notifications][version] = "2.3"
projects[onbeforeunload][version] = "1.0"
projects[openid_selector][version] = "1.5"
projects[panels][version] = "3.10"
projects[pathauto][version] = "1.6"
projects[permissions_api][version] = "2.12"
projects[print][version] = "1.14"
projects[profile_permission][version] = "1.2"
projects[recaptcha][version] = "1.7"
projects[services][version] = "3.1"
projects[rules][version] = "1.4"
projects[schema][version] = "1.7"
projects[sshkey][version] = "2.0-beta2"
projects[stringoverrides][version] = "1.8"
projects[subscriptions][version] = "1.4"
projects[terms_of_use][version] = "1.13"
projects[token][version] = "1.18"
projects[url_alter][version] = "1.2"
projects[views][version] = "2.16"
projects[views_bonus][version] = "1.1"
projects[views_customfield][version] = "1.0"
projects[views_data_export][version] = "2.0-beta5"
projects[views_export_xls][version] = "1.1-beta1"
projects[views_or][version] = "1.x-dev"
projects[views_rss][version] = "1.0-beta5"
projects[views_watchdog][version] = "2.3"
projects[votingapi][version] = "2.3"
projects[webform][version] = "3.15"
projects[workflow][version] = "1.5"
projects[wysiwyg][version] = "2.4"

; Themes
projects[litejazz][version] = "1.7"

; Custom modules from GIT repo http://github.com/futuregrid/portal
;projects[fg_phase_2][download][type] = "git"
;projects[fg_phase_2][download][url] = "git://github.com/futuregrid/portal.git"
;projects[fg_phase_2][type] = "module"

;projects[iukb][download][type] = "git"
;projects[iukb][download][url] = "git://github.com/futuregrid/portal.git"
;projects[iukb][type] = "module"

; Custom module
; NOTE: this module contains sensitive info and so is not in the repo
; Copy this module off the production machine
;projects[fgutil][download][type] = ""
;projects[fgutil][download][url] = ""
;projects[fgutil][type] = "module"

; Libraries
libraries[openid-selector][download][type] = "get"
libraries[openid-selector][download][url] = "http://openid-selector.googlecode.com/files/openid-selector-1.3.zip"
libraries[openid-selector][directory_name] = "openid-selector"
libraries[openid-selector][type] = "library"

libraries[jquery_ui_smoothness][download][type] = "get"
libraries[jquery_ui_smoothness][download][url] = "http://jquery-ui.googlecode.com/files/jquery-ui-themes-1.7.3.zip"
libraries[jquery_ui_smoothness][directory_name] = "jquery_ui_smoothness"
libraries[jquery_ui_smoothness][type] = "library"

libraries[jquery.ui][download][type] = "get"
libraries[jquery.ui][download][url] = "http://jquery-ui.googlecode.com/files/jquery-ui-1.7.3.zip"
libraries[jquery.ui][directory_name] = "jquery.ui"
libraries[jquery.ui][type] = "library"

libraries[dompdf][download][type] = "get"
libraries[dompdf][download][url] = "http://dompdf.googlecode.com/files/dompdf-0.5.2.zip"
libraries[dompdf][directory_name] = "dompdf"
libraries[dompdf][type] = "library"

libraries[datatables][download][type] = "get"
libraries[datatables][download][url] = "http://datatables.net/releases/DataTables-1.9.0.zip"
libraries[datatables][directory_name] = "datatables"
libraries[datatables][type] = "library"

; use drush to download ckeditor:
; $> drush ckeditor-download
;libraries[ckeditor][download][type] = ""
;libraries[ckeditor][download][url] = ""
;libraries[ckeditor][directory_name] = "ckeditor"
;libraries[ckeditor][type] = "library"
