<?php
$plugin = array(
  'title' => t('Front page layout'),
  'category' => t('FutureGrid'),
  'icon' => 'frontpagelayout.png',
  'theme' => 'frontpagelayout',
  'css' => 'frontpagelayout.css',
  'js' => 'frontpagelayout.js',
  'panels' => array(
    'carousel' => t('Featured'),
    'accordion' => t('Blog'),
    'news' => t('News'),
    'projects' => t('Projects'),
    'support' => t('Support')
  ),
);
